apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  username: dXNlcm5hbWUxMjM0   # Base64 encoded username: "username1234"
  password: cGFzc3dvcmQxMjM0   # Base64 encoded password: "password1234"
