apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mycustomresources.example.com
spec:
  group: example.com
  version: v1
  scope: Namespaced
  names:
    plural: mycustomresources
    singular: mycustomresource
    kind: MyCustomResource
    shortNames:
    - mcr
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          properties:
            foo:
              type: string
            bar:
              type: integer
          required:
          - foo
  additionalPrinterColumns:
  - name: Foo
    type: string
    description: Foo description
    JSONPath: .spec.foo
  - name: Bar
    type: integer
    description: Bar description
    JSONPath: .spec.bar
